export const ingredientsList = [
  "prebiotics",
  "matcha",
  "hyaluronic_acid",
  "prebiotics_blue",
  "shea_butter",
  "moringa_oil",
  "pre_prebiotics",
  "pomegranate",
  "aloe_vera",
  "time_to_repair_prebiotics",
  "collagen_booster",
  "thistle_oil",
  "happy_age_prebiotics",
  "happy_age_hyaluronic_acid",
  "stevia_oil",
  "prebiotic_ferment",
  "vegetal_retinol",
  "golden_seaweed_extract",
  "go_for_detox_prebiotics",
  "turmeric_root_extract",
  "organic_artichoke_leaf",
  "go_for_protection_dietary_prebiotics",
  "go_for_protection_dietary_prebiotics_combination",
  "vitamins",
] as const

export const productsList = [
  "go_for_protection_skincare",
  "time_to_detox",
  "go_for_glow",
  "time_to_repair",
  "happy_age",
  "sculpt_glow",
  "go_for_detox",
  "go_for_protection_dietary",
] as const
